#!/bin/bash

config=$1
metrics_file=$2

results_dir="../results"
dashes="-----------------------"
cat $metrics_file | while read metric; do
  printf "%s\n%s\n%s\n" $dashes "$metric" $dashes
  output_file=$results_dir/$config/$(echo $metric | tr -d '[[:space:]]').out
  if [ -f $output_file ]; then
    rm $output_file
  fi

  for benchmark in $results_dir/$config/*eio.gz.out; do
    value=$(cat $benchmark | sed -nre "s/$metric[ ]+([\.0-9]+).*/\1/p")
    printf "%40s\t%5f\n" $(basename $benchmark) $value >> $output_file
  done

  ./average $output_file | tee -a $output_file
  printf "\n\n"
done

